dist: xenial

services:
  - docker

script: ./travis/build.sh

before_cache:
  - rm -f  .gradle-cache/caches/modules-2/modules-2.lock
  - rm -fr .gradle-cache/caches/*/plugin-resolution/
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.bin
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - .gradle-cache/caches/
    - .gradle-cache/wrapper/
