services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version

jobs:
  include:
    - stage: build
      script: ./batect build

    - stage: unit test
      script: ./batect unitTest

    - stage: integration test
      script: ./batect integrationTest

    - stage: journey test
      script: ./batect journeyTest

    - stage: push image
      script: ./batect pushImage

before_cache:
  - rm -f  .gradle-cache/caches/modules-2/modules-2.lock
  - rm -fr .gradle-cache/caches/*/plugin-resolution/
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.bin
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - .gradle-cache/caches/
    - .gradle-cache/wrapper/
