#!/usr/bin/env bash

set -euo pipefail

VERSION="0.10"
DOWNLOAD_URL=${BATECT_DOWNLOAD_URL:-"https://github.com/charleskorn/batect/releases/download/0.10/batect-0.10.jar"}

ROOT_CACHE_DIR=${BATECT_CACHE_DIR:-"$HOME/.batect/cache"}
CACHE_DIR="$ROOT_CACHE_DIR/$VERSION"
JAR_PATH="$CACHE_DIR/batect-$VERSION.jar"

function main() {
    if ! haveVersionCachedLocally; then
        download
    fi

    runApplication "$@"
}

function haveVersionCachedLocally() {
    [ -f "$JAR_PATH" ]
}

function download() {
    echo "Downloading batect version $VERSION from $DOWNLOAD_URL..."

    if ! hash curl 2>/dev/null; then
        echo "curl is not installed or not on your PATH. Please install it and try again." >&2
        exit -1
    fi

    mkdir -p "$CACHE_DIR"
    temp_file=$(mktemp)
    curl -# --fail --show-error --location --output "$temp_file" "$DOWNLOAD_URL"
    mv "$temp_file" "$JAR_PATH"
}

function runApplication() {
    if ! hash java 2>/dev/null; then
        echo "Java is not installed or not on your PATH. Please install it and try again." >&2
        exit -1
    fi

    java -jar "$JAR_PATH" "$@"
}

main "$@"
